# Generated by Django 3.2 on 2021-12-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ice',
            new_name='Book',
        ),
    ]
